### ISSUE TITLE
no support for nn.Linear

### ISSUE THREAD

**Issue by Hunger-Prevails** [khcs/fp16-demo-tf#2]
Hi, thanks for your code.

the problem is that I seem to encounter this error when trying to use your code:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liu/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/liu/.local/lib/python2.7/site-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/liu/.local/lib/python2.7/site-packages/torch/nn/functional.py", line 1352, in linear
    ret = torch.addmm(torch.jit._unwrap_optional(bias), input, weight.t())
RuntimeError: s__th_addmm is not implemented for type torch.HalfTensor

did you encounter this and fixed it or?

**Comment by Hunger-Prevails** [comment]
and I encounter this 'not implemented' error for all my layers....
